# Generated by Django 5.1.2 on 2024-11-03 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_achievement_created_in_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='created_in_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gameversion', verbose_name='Créer en version'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='updated_for_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_achievements', to='app.gameversion', verbose_name='Mis à jour lors de la version'),
        ),
    ]
