# Generated by Django 5.1.2 on 2024-11-04 17:32

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_achievementquest_achievement_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['title'], 'verbose_name': 'Succès', 'verbose_name_plural': 'Succès'},
        ),
        migrations.AlterModelOptions(
            name='alignment',
            options={'ordering': ['id'], 'verbose_name': 'Alignement', 'verbose_name_plural': 'Alignements'},
        ),
        migrations.AlterModelOptions(
            name='commonspell',
            options={'ordering': ['name'], 'verbose_name': 'Sort commun', 'verbose_name_plural': 'Sorts communs'},
        ),
        migrations.AlterModelOptions(
            name='guide',
            options={'ordering': ['id'], 'verbose_name': 'Guide', 'verbose_name_plural': 'Guides'},
        ),
        migrations.AlterModelOptions(
            name='guideachievement',
            options={'verbose_name': 'Guide - Succès', 'verbose_name_plural': 'Guide - Succès'},
        ),
        migrations.AlterModelOptions(
            name='quest',
            options={'ordering': ['title'], 'verbose_name': 'Quête', 'verbose_name_plural': 'Quêtes'},
        ),
        migrations.AlterField(
            model_name='achievement',
            name='updated_for_version',
            field=models.FloatField(blank=True, default=Decimal('2.73'), null=True, verbose_name='Mis à jour lors de la version'),
        ),
        migrations.AlterField(
            model_name='achievementquest',
            name='achievement',
            field=models.ForeignKey(help_text='Le succès auquel cette quête est liée', on_delete=django.db.models.deletion.CASCADE, to='app.achievement', verbose_name='Succès'),
        ),
        migrations.AlterField(
            model_name='achievementquest',
            name='quest',
            field=models.ForeignKey(help_text='La quête à réaliser pour ce succès', on_delete=django.db.models.deletion.CASCADE, to='app.quest', verbose_name='Quêtes'),
        ),
        migrations.AlterField(
            model_name='alignment',
            name='name',
            field=models.CharField(help_text="Nom de l'alignement", max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='updated_for_version',
            field=models.FloatField(blank=True, default=Decimal('2.73'), null=True, verbose_name='Mis à jour lors de la version'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='alignment',
            field=models.ForeignKey(default=3, help_text="L'alignement requis pour cette quête", on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='app.alignment', verbose_name='Alignement'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='completed',
            field=models.BooleanField(default=False, help_text='La quête a-t-elle été complétée ?', verbose_name='Complété ?'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='title',
            field=models.CharField(help_text='Le titre unique de la quête', max_length=100, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='updated_for_version',
            field=models.FloatField(blank=True, default=Decimal('2.73'), null=True, verbose_name='Mis à jour lors de la version'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='url',
            field=models.URLField(help_text='URL de la page DPLN de la quête', max_length=255),
        ),
    ]
