# Generated by Django 5.1.2 on 2024-11-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_achievement_options_alter_alignment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='objectives',
            field=models.TextField(max_length=255, verbose_name='Objectifs'),
        ),
    ]
