# Generated by Django 5.0.2 on 2024-11-08 17:00

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_guide_objectives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='explanations',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='objectives',
            field=django_ckeditor_5.fields.CKEditor5Field(max_length=255, verbose_name='Text'),
        ),
    ]
