# Generated by Django 5.0.2 on 2024-11-08 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_guide_objectives'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='important_info',
            field=models.TextField(blank=True, null=True, verbose_name='A prévoir'),
        ),
        migrations.CreateModel(
            name='Dungeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('level', models.IntegerField(verbose_name='Niveau')),
                ('url', models.URLField(blank=True, null=True)),
                ('captured', models.BooleanField(default=False, help_text='Le donjon a-t-il été capturé ?', verbose_name='Capturé ?')),
                ('completed', models.BooleanField(default=False, help_text='Le donjon a-t-il été complété ?', verbose_name='Complété ?')),
                ('guide', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dungeons_guide', to='app.guide')),
            ],
            options={
                'verbose_name': 'Donjon',
                'verbose_name_plural': 'Donjons',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DungeonQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dungeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dungeon', verbose_name='Donjon')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.quest', verbose_name='Quête')),
            ],
            options={
                'verbose_name': 'Donjon - Quête',
                'verbose_name_plural': 'Donjon - Quêtes',
                'db_table': 'dungeon_quest',
                'unique_together': {('dungeon', 'quest')},
            },
        ),
        migrations.AddField(
            model_name='quest',
            name='dungeon',
            field=models.ManyToManyField(related_name='quests', through='app.DungeonQuest', to='app.dungeon'),
        ),
    ]
