# Generated by Django 5.0.2 on 2024-11-08 20:25

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_guide_explanations_alter_guide_objectives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='explanations',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Guide'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='objectives',
            field=django_ckeditor_5.fields.CKEditor5Field(max_length=255, verbose_name='Objectifs'),
        ),
        migrations.CreateModel(
            name='Dungeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('level', models.IntegerField(verbose_name='Niveau')),
                ('url', models.URLField(blank=True, null=True)),
                ('captured', models.BooleanField(default=False, help_text='Le donjon a-t-il été capturé ?', verbose_name='Capturé ?')),
                ('completed', models.BooleanField(default=False, help_text='Le donjon a-t-il été complété ?', verbose_name='Complété ?')),
                ('guide', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dungeons', to='app.guide')),
            ],
            options={
                'verbose_name': 'Donjon',
                'verbose_name_plural': 'Donjons',
                'ordering': ['name'],
            },
        ),
    ]
