# Generated by Django 5.0.2 on 2024-11-08 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_guide_explanations_alter_guide_objectives_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DungeonQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dungeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dungeon', verbose_name='Donjon')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.quest', verbose_name='Quête')),
            ],
            options={
                'verbose_name': 'Donjon - Quête',
                'verbose_name_plural': 'Donjon - Quêtes',
                'db_table': 'dungeon_quest',
                'unique_together': {('dungeon', 'quest')},
            },
        ),
    ]
