# Generated by Django 5.0.2 on 2024-11-08 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_dungeonquest'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='dungeon',
            field=models.ManyToManyField(related_name='quests', through='app.DungeonQuest', to='app.dungeon'),
        ),
        migrations.AlterField(
            model_name='dungeon',
            name='guide',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dungeons_guide', to='app.guide'),
        ),
    ]
