# Generated by Django 5.1.2 on 2024-11-03 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
                ('completion_points', models.IntegerField()),
                ('objectives', models.TextField(max_length=255)),
                ('expect_ressource', models.BooleanField(default=False)),
                ('expect_item', models.BooleanField(default=False)),
                ('expect_fight', models.BooleanField(default=False)),
                ('expect_dungeon', models.BooleanField(default=False)),
                ('expect_job', models.BooleanField(default=False)),
                ('expect_other', models.BooleanField(default=False)),
                ('expect_alignment', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_in_version', models.FloatField(default=2.73)),
                ('updated_for_version', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('objectives', models.CharField(max_length=255)),
                ('explanations', models.TextField(blank=True, null=True)),
                ('page', models.IntegerField()),
                ('recommended_level', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_in_version', models.FloatField(default=2.73)),
                ('updated_for_version', models.FloatField(blank=True, null=True)),
                ('alignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guides', to='app.alignment')),
            ],
        ),
        migrations.CreateModel(
            name='CommonSpell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('obtainment', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('guide', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='common_spells', to='app.guide')),
            ],
        ),
        migrations.CreateModel(
            name='GuideAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.achievement')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.guide')),
            ],
            options={
                'db_table': 'guide_achievement',
                'unique_together': {('guide', 'achievement')},
            },
        ),
        migrations.AddField(
            model_name='guide',
            name='achievement',
            field=models.ManyToManyField(through='app.GuideAchievement', to='app.achievement'),
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_in_version', models.FloatField(default=2.73)),
                ('updated_for_version', models.FloatField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('alignment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='app.alignment')),
            ],
        ),
        migrations.CreateModel(
            name='AchievementQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.achievement')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.quest')),
            ],
            options={
                'db_table': 'achievement_quest',
                'unique_together': {('achievement', 'quest')},
            },
        ),
        migrations.AddField(
            model_name='achievement',
            name='quests',
            field=models.ManyToManyField(through='app.AchievementQuest', to='app.quest'),
        ),
    ]
