# Generated by Django 5.1.2 on 2024-11-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='objectives',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
