# Generated by Django 5.1.2 on 2024-11-03 14:14

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_achievement_options_alter_guide_achievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='completion_points',
            field=models.IntegerField(verbose_name='Point de succès'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='created_in_version',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.73'), max_digits=5, verbose_name='Créer en version'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='expect_alignment',
            field=models.BooleanField(default=False, verbose_name='Demande : Alignement'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='expect_dungeon',
            field=models.BooleanField(default=False, verbose_name='Demande : Donjon'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='expect_fight',
            field=models.BooleanField(default=False, verbose_name='Demande : Combat'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='expect_item',
            field=models.BooleanField(default=False, verbose_name='Demande : Item'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='expect_job',
            field=models.BooleanField(default=False, verbose_name='Demande : Métier'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='expect_other',
            field=models.BooleanField(default=False, verbose_name='Demande : Autre'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='expect_ressource',
            field=models.BooleanField(default=False, verbose_name='Demande : Ressource'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='objectives',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Objectifs'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='quests',
            field=models.ManyToManyField(related_name='achievements', through='app.AchievementQuest', to='app.quest'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='title',
            field=models.CharField(max_length=255, verbose_name='titre'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='updated_for_version',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Mis à jour lors de la version'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='alignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='app.alignment', verbose_name='Alignement'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Complété ?'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Titre'),
        ),
    ]
