# Generated by Django 5.1.2 on 2024-11-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_achievement_completion_points_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='achievement',
            name='created_in_version',
            field=models.FloatField(default='', verbose_name='Créer en version'),
        ),
    ]
