# Generated by Django 5.1.2 on 2024-11-03 16:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_achievement_created_in_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='created_in_version',
            field=models.FloatField(default=Decimal('2.73'), verbose_name='Créer en version'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='updated_for_version',
            field=models.FloatField(blank=True, null=True, verbose_name='Mis à jour lors de la version'),
        ),
        migrations.DeleteModel(
            name='GameVersion',
        ),
    ]
