# Generated by Django 5.1.2 on 2024-11-03 16:38

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_achievement_created_in_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementquest',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.achievement', verbose_name='Succès'),
        ),
        migrations.AlterField(
            model_name='achievementquest',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.quest', verbose_name='Quêtes'),
        ),
        migrations.AlterField(
            model_name='alignment',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='commonspell',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='commonspell',
            name='obtainment',
            field=models.CharField(max_length=255, verbose_name='Obtention'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='alignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guides', to='app.alignment', verbose_name='Alignement'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='created_in_version',
            field=models.FloatField(default=Decimal('2.73'), verbose_name='Créer en version'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='explanations',
            field=models.TextField(blank=True, null=True, verbose_name='Guide'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='objectives',
            field=models.CharField(max_length=255, verbose_name='Objectifs'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='page',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='guide',
            name='recommended_level',
            field=models.IntegerField(verbose_name='Niveau recommandé'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='updated_for_version',
            field=models.FloatField(blank=True, null=True, verbose_name='Mis à jour lors de la version'),
        ),
        migrations.AlterField(
            model_name='guideachievement',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.achievement', verbose_name='Succès'),
        ),
        migrations.AlterField(
            model_name='guideachievement',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.guide', verbose_name='Guide'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='created_in_version',
            field=models.FloatField(default=Decimal('2.73'), verbose_name='Créer en version'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='updated_for_version',
            field=models.FloatField(blank=True, null=True, verbose_name='Mis à jour lors de la version'),
        ),
    ]
