# Generated by Django 5.0.2 on 2024-11-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_lastsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideachievement',
            name='is_last_seen',
            field=models.BooleanField(default=False),
        ),
    ]
