# Generated by Django 5.0.2 on 2024-11-21 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_guideachievement_is_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='is_last_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='guideachievement',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievement_guides', to='app.achievement', verbose_name='Succès'),
        ),
        migrations.AlterField(
            model_name='guideachievement',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_achievements', to='app.guide', verbose_name='Guide'),
        ),
        migrations.DeleteModel(
            name='LastSession',
        ),
    ]
