# Generated by Django 5.0.2 on 2024-11-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_achievement_is_last_seen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='is_last_seen',
        ),
        migrations.AddField(
            model_name='guide',
            name='is_last_seen',
            field=models.BooleanField(default=False),
        ),
    ]
