# Generated by Django 5.0.2 on 2024-11-22 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_achievement_is_last_seen_guide_is_last_seen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='expect_ressource',
            new_name='expect_resource',
        ),
    ]
