# Generated by Django 5.0.2 on 2024-11-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_expect_ressource_achievement_expect_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='objectives',
            field=models.TextField(blank=True, null=True, verbose_name='Objectifs'),
        ),
    ]
