# Generated by Django 5.0.2 on 2024-11-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_guide_objectives'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='expect_capture',
            field=models.BooleanField(default=False, verbose_name='Demande : Capture'),
        ),
    ]
