# Generated by Django 5.0.2 on 2024-11-24 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_achievement_expect_capture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quest',
            options={'ordering': ['id'], 'verbose_name': 'Quête', 'verbose_name_plural': 'Quêtes'},
        ),
    ]
