# Generated by Django 5.0.2 on 2024-11-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_quest_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='important_info',
            field=models.TextField(blank=True, null=True, verbose_name='Informations importantes'),
        ),
    ]
