# Generated by Django 5.0.2 on 2024-11-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_guide_important_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
