# Generated by Django 5.0.9 on 2024-12-05 15:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_guide_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='created_in_version',
            field=models.FloatField(default=Decimal('3.0'), verbose_name='Créer en version'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='updated_for_version',
            field=models.FloatField(blank=True, default=Decimal('3.0'), null=True, verbose_name='Mis à jour lors de la version'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='created_in_version',
            field=models.FloatField(default=Decimal('3.0'), verbose_name='Créer en version'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='updated_for_version',
            field=models.FloatField(blank=True, default=Decimal('3.0'), null=True, verbose_name='Mis à jour lors de la version'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='created_in_version',
            field=models.FloatField(default=Decimal('3.0'), verbose_name='Créer en version'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='updated_for_version',
            field=models.FloatField(blank=True, default=Decimal('3.0'), null=True, verbose_name='Mis à jour lors de la version'),
        ),
    ]
