# Generated by Django 5.0.9 on 2024-12-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_achievement_created_in_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='position',
            field=models.PositiveIntegerField(help_text='Position de la quête par rapport aux autres du succès', null=True),
        ),
    ]
