# Generated by Django 5.0.9 on 2024-12-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_quest_options_alter_quest_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='position',
            field=models.PositiveIntegerField(blank=True, help_text='Position de la quête par rapport aux autres du succès', null=True),
        ),
    ]
