# Generated by Django 5.0.10 on 2024-12-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_quest_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
