# Generated by Django 5.0.10 on 2024-12-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_guide_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Visible'),
        ),
    ]
