# Generated by Django 5.0.10 on 2025-02-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_guide_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='recommended_level',
            field=models.IntegerField(blank=True, null=True, verbose_name='Niveau recommandé'),
        ),
    ]
